"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultRoute = void 0;
const express_1 = require("express");
const build_1 = require("../controller/build");
const manageFiles_1 = require("../controller/manageFiles");
exports.defaultRoute = (0, express_1.Router)();
exports.defaultRoute.get('/ping', build_1.Controller.ping);
exports.defaultRoute.post('/ping', build_1.Controller.buildTemplate);
exports.defaultRoute.post('/upload', build_1.Controller.uploadTemplate);
exports.defaultRoute.get('/listfile', manageFiles_1.ControllerFiles.listFiles);
exports.defaultRoute.get('/listimg', manageFiles_1.ControllerFiles.listImages);
exports.defaultRoute.get('/listdoc', manageFiles_1.ControllerFiles.listDocs);
exports.defaultRoute.get('/listvideos', manageFiles_1.ControllerFiles.listVideos);
